apiVersion: v1
kind: Secret
metadata:
  name: api-go-secret
  namespace: mlops-apps
type: Opaque
stringData:
  MINIO_ENDPOINT: http://minio.mlops-infra.svc.cluster.local:9000
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio12345
  MINIO_BUCKET: predictions
  PREDICTIONS_KEY: predictions_latest.csv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go
  namespace: mlops-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-go
  template:
    metadata:
      labels:
        app: api-go
    spec:
      containers:
      - name: api
        image: api-go-local:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: api-go-secret
        ports:
        - containerPort: 8080
        env:
        - name: MINIO_ENDPOINT
          value: minio.mlops-infra.svc.cluster.local:9000
        - name: MINIO_USE_SSL
          value: "false"
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          value: minio12345
        - name: PREDICTIONS_BUCKET
          value: predictions
        - name: PREDICTIONS_KEY_TEMPLATE
          value: "{ticker}/H{h}/predictions_test.csv"
---
apiVersion: v1
kind: Service
metadata:
  name: api-go
  namespace: mlops-apps
spec:
  selector:
    app: api-go
  ports:
  - name: http
    port: 8080
    targetPort: 8080
